# 请求URL指向Eureka服务治理中心
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.103:5001/eureka
  instance:
    hostname: 192.168.0.103

# 微服务端口
server:
  port: 6001

# 应用名称
spring:
  application:
    name: user
