# 请求URL指向Eureka服务治理中心
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.103:5001/eureka,http://192.168.0.103:5002/eureka
  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10

# 微服务端口
server:
  port: 7001

# 应用名称
spring:
  application:
    name: fund
