# 定义Spring应用名称，他是一个微服务的名称，一个微服务可以拥有多个实例
spring:
  application:
    name: eureka-server

server:
  port: 5001
eureka:
  client:
    # 服务自身就是治理中心，所以这里设置为false,取消注册
    register-with-eureka: false
    # 取消服务获取
    fetch-registry: false
  #    serviceUrl:
#     defaultZone: http://127.0.0.1:5002/eureka
  instance:
    hostname: 192.168.0.103